package cu.ondev.nuestraradio.utilities

object RadioPosterUrl {

    val BASE_POSTER_URL = "https://cdn.teveo.cu/media/live/audio/poster-SD-"

    val radioNames = arrayOf(
        "Radio Rebelde",
        "Radio Progreso",
        "Radio Habana Cuba",
        "Radio Reloj",
        "Radio Taíno",
        "Radio Santa Clara",
        "Radio Ciudad del Mar",
        "Radio Angulo CMKO",
        "Radio Artemisa",
        "Radio Bayamo CMKX",
        "Radio Cadena Agramonte",
        "Radio COCO",
        "Radio Mayabeque",
        "Radio Sancti Spíritus",
        "Radio Surco",
        "Radio Victoria",
        "Aguada Radio",
        "La Voz del Litoral",
        "La Voz del Níquel",
        "La Voz del,a",
        "Radio Baracoa",
        "Radio Metropolitana",
        "Radio Banes CMKM",
        "Radio 26 | CMGW",
        "Radio Amanecer",
        "Radio Arimao",
        "Radio Bahía",
        "Radio Baraguá",
        "Radio Cabaiguán",
        "Radio Cabaniguán",
        "Radio Cadena Habana",
        "Radio Caibarién",
        "Radio Camagüey",
        "Radio Camoa",
        "Radio Caribe CMBN",
        "Radio Chambas",
        "Radio Chaparras",
        "Radio Ciudad Bandera",
        "Radio Ciudad Monumento",
        "Radio CMKC",
        "Radio Cubitas",
        "Radio Cumanayagua",
        "Radio Ecos de Sagua",
        "Radio Enciclopedia",
        "Radio Estéreo Centro",
        "Radio Fomento",
        "Radio Gibara",
        "Radio Granma CMDF",
        "Radio Grito de Baire",
        "Radio Guáimaro",
        "Radio Guamá",
        "Radio Holguín CMKE",
        "Radio Jaruco",
        "Radio Jiguaní CMND",
        "Radio Juvenil",
        "Radio Victoria",
        "Radio Libertad",
        "Radio Llanura de Colón",
        "Radio Maisí",
        "Radio Majaguabo",
        "Radio Manatí",
        "Radio Mayarí CMKN",
        "Radio Minas",
        "Radio Musical Nacional",
        "Radio Nuevitas",
        "Radio Placetas",
        "Radio Playitas",
        "Radio Sagua",
        "Radio Sandino",
        "Radio Santa Cruz",
        "Radio Sibanicú",
        "Radio Siboney",
        "Radio Sonido SM",
        "Radio Titán",
        "Radio Trinchera CMKS",
        "Radio Trinchera",
        "Radio Vertientes",
        "Radio Victoria de Girón",
    )

    val radioPosterUrl = arrayOf(
        "Kd2na3tNDhE29fu8.jpg",
        "kbPxRfVfdPzpqamV.jpg",
        "D83sK4eBpbQ5NmkY.jpg",
        "n5FpSnw8jmC9UCMB.jpg",
        "p6UcMpNbK9SK88Pb.jpg",
        "2g9nhTVKeuQtVhmM.jpg",
        "rQWbtbuZ3JyJ3wWQ.jpg",
        "ABGHCXqDR5AtQ7kt.jpg",
        "9xnfjDkHFvARQd66.jpg",
        "RGbKVb82K2QjHDzJ.jpg",
        "WgvGNPKuAxPdZA5R.jpg",
        "9Wg6XEaKpGJGgVpQ.jpg",
        "gJP6Zjx8G2z8NPGC.jpg",
        "nUHFy4JNHDgz8ksW.jpg",
        "MRbRKzq4Z3Q5tUCP.jpg",
        "Hb7xbfXm3zvsnQTZ.jpg",
        "XTAUF5zbmMMSMZBZ.jpg",
        "VQTYBSKsmQK2gqGN.jpg",
        "ASn3eBPvyh6V73r2.jpg",
        "bhAC5x9TpP2jc8dZ.jpg",
        "bhAC5x9TpP2jc8dZ.jpg",
        "bwYbZTAY799K87ea.jpg",
        "K45QbW5ZygfRPbEJ.jpg",
        "qj26njX7dBkggwtN.jpg",
        "QhCYzy5rdsVhPVH3.jpg",
        "bZ4BMa3aUHXxJqcw.jpg",
        "FEsmERt7nfcn3dMz.jpg",
        "pmZqeeGXnXjJxXzG.jpg",
        "pvFQMR5exXkfyZQM.jpg",
        "jygJmftT5vZ7w8eB.jpg",
        "nbdEb6Uq8aXj6VQe.jpg",
        "4RParVtBfsQrqACt.jpg",
        "RcSVtydggunhj4EY.jpg",
        "xY7SPU2CrtScj67V.jpg",
        "7KPj9JVq9mSnbpUN.jpg",
        "TJWBVN3T2dUdghes.jpg",
        "NwJvArGUENkUj99h.jpg",
        "FD5qHNXns6K6xsTG.jpg",
        "nB2JDx9XajSqxnXk.jpg",
        "GQMgsrMu43ndU9kR.jpg",
        "EKgdaP5kj52S3XsP.jpg",
        "vGyYxEKbHsZ8uAbJ.jpg",
        "aGqwbzMMSBz9GZbt.jpg",
        "ZK3J8eUMga4VM6kv.jpg",
        "xJc9zxcWnwSJXbu2.jpg",
        "we8eSxSFrteJcGEC.jpg",
        "zYusXxEHQRP5a738.jpg",
        "XkXsh2QJr4MyRdF8.jpg",
        "xc9skjfcARevQ2pp.jpg",
        "dxJRZMmkCf3PgHF3.jpg",
        "babapknyVmPJK9FP.jpg",
        "6w5kxqASymaW93aH.jpg",
        "DjHk3gMCmGESKUke.jpg",
        "zRNkz9GE7qN2v9uT.jpg",
        "svpWEVzJzwqR8Dj9.jpg",
        "KubswNAtksUYC9HC.jpg",
        "UtfyTwkvDCnP3fu4.jpg",
        "eVYHWyzaedJd8d9Z.jpg",
        "5Ufexswv7ZAaMMgr.jpg",
        "TGtasJjKdbqZbb2Z.jpg",
        "WjTARpDzmhE6aEvs.jpg",
        "ybtgWCrFGUZGgwYh.jpg",
        "26UdjeU7pdPRmP7Z.jpg",
        "D9cEuVwM4sQtCMUs.jpg",
        "sgRShURhf4w3mAqT.jpg",
        "QTq84GWXDswQs97p.jpg",
        "8xpzdRcjWrsJmS9E.jpg",
        "vfUBAHKR72DEtnuC.jpg",
        "gJqJWeGbawNxRu3F.jpg",
        "Jcn6HhnzjQNMHA3B.jpg",
        "MrP2TGspHRCCujjU.jpg",
        "cKakgvvC7QQWYyMG.jpg",
        "2p5eeBQ4ahCW2vUY.jpg",
        "ztqwFNfPjbWFSKbZ.jpg",
        "gHujG3CHD9pf7t2C.jpg",
        "gHujG3CHD9pf7t2C.jpg",
        "4NrVjs9pkafGsssh.jpg",
        "nqVx5axF2FT5ftrU.jpg",
    )

    fun getRadioPoster(radioName: String): String? {
        var radioNameIndex = -1

        (radioNames.indices).forEach { i: Int ->
            if (radioNames[i] == radioName) {
                radioNameIndex = i
            }
        }
        return when {
            radioNameIndex != -1 -> {
                BASE_POSTER_URL + radioPosterUrl[radioNameIndex]
            }
            else -> {
                null
            }
        }
    }

}